// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAom0sdSbkPUTNzVPcC5zE1NOTggjii_1M',
    appId: '1:991411930094:android:0355449f322a95142484ff',
    messagingSenderId: '991411930094',
    projectId: 'mecourse-9f591',
    storageBucket: 'mecourse-9f591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQSd6SF8YnRscOTviDWzkyYMn_8QazeM',
    appId: '1:991411930094:ios:6c48ff8901689ae72484ff',
    messagingSenderId: '991411930094',
    projectId: 'mecourse-9f591',
    storageBucket: 'mecourse-9f591.appspot.com',
    androidClientId: '991411930094-485oojaf2dciprqs1vr8ok7imlg27phj.apps.googleusercontent.com',
    iosClientId: '991411930094-u14chmmjq60v3lm06lp3bdhul6udhjdc.apps.googleusercontent.com',
    iosBundleId: 'com.abdelhamidmergh.medcourse',
  );
}
